# Generated by Django 4.2.16 on 2026-08-31 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0003_usertimetableexporttheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ref_semester', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimPlanCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='simulation.simplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='simplancollect',
            constraint=models.UniqueConstraint(fields=('plan', 'course_id'), name='plan_course_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='simplan',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_plan_name_unique'),
        ),
    ]
