# Generated by Django 4.2.16 on 2026-08-31 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0004_simplan_simplancollect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCustomCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=5)),
                ('name', models.CharField(max_length=60)),
                ('teacher', models.CharField(blank=True, max_length=60)),
                ('time', models.CharField(blank=True, max_length=60)),
                ('room', models.CharField(blank=True, max_length=60)),
                ('credit', models.FloatField(default=0)),
                ('color', models.CharField(default='#aebed1', max_length=7)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_courses', to='simulation.simplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_custom_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
